CREATE TABLE IF NOT EXISTS "posts" (
  "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(100),
  "content" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);